groups:
- name: node_usage_record_rules
  interval: 1m
  rules:
  - record: cpu:usage:rate1m
    expr: (1 - avg(rate(node_cpu_seconds_total{mode="idle"}[1m])) by (instance,vendor,account,group,name)) * 100
  - record: mem:usage:rate1m
    expr: (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100

- name: Linux服务器状态-告警
  rules:
  - alert: VM内存使用率
    expr: 100 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100 > 90
    for: 5m
    labels:
      alertype: system
      severity: warning
    annotations:
      description: "**{{ $labels.name }}：内存使用率{{ $value | humanize }}%**  \n  > {{ $labels.group }}-{{ $labels.instance }}"

  - alert: VM_CPU使用率
    expr: 100 - (avg by(instance,name,group,account) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
    for: 5m
    labels:
      alertype: system
      severity: warning
    annotations:
      description: "**{{ $labels.name }}：CPU使用率{{ $value | humanize }}%**  \n  > {{ $labels.group }}-{{ $labels.instance }}"

  - alert: VM系统负载
    expr: node_load5 / on (instance,name,group,account) sum(count(node_cpu_seconds_total{mode='system'}) by (cpu,instance,name,group,account)) by(instance,name,group,account) > 1.7
    for: 10m
    labels:
      alertype: system
      severity: warning
    annotations:
      description: "**{{ $labels.name }}：系统负载{{ $value | humanize }}倍**  \n  > {{ $labels.group }}-{{ $labels.instance }}"

  - alert: VM磁盘使用率
    expr: |
      100 - (node_filesystem_avail_bytes/node_filesystem_size_bytes{fstype=~"ext.?|xfs",mountpoint!~".*pods.*|/var/lib/docker/devicemapper/mnt/.*"} * 100) > 85
    for: 5m
    labels:
      alertype: system
      severity: warning
    annotations:
      description: "**{{ $labels.name }}_{{ $labels.mountpoint }}：磁盘使用率{{ $value | humanize }}%**  \n  > {{ $labels.group }}-{{ $labels.instance }}"

  - alert: VM主机重启
    expr: node_time_seconds - node_boot_time_seconds < 600
    for: 1m
    labels:
      alertype: system
      severity: warning
    annotations:
      description: "**{{ $labels.name }}：主机重启**  \n  > {{ $labels.group }}-{{ $labels.instance }}"

  - alert: VM文件系统只读
    expr: node_filesystem_readonly == 1
    for: 1m
    labels:
      alertype: system
      severity: warning
    annotations:
      description: "**{{ $labels.name }}-{{ $labels.mountpoint }}：文件系统只读**  \n  > {{ $labels.group }}-{{ $labels.instance }}"

  - alert: K8S节点POD磁盘使用率
    expr: 100 - (node_filesystem_avail_bytes/node_filesystem_size_bytes{mountpoint=~"/var/lib/docker/devicemapper/mnt/.*"} * 100) > 85
    for: 5m
    labels:
      alertype: system
      severity: warning
    annotations:
      description: "**{{ $labels.name }}_{{ $labels.mountpoint }}：磁盘使用率{{ $value | humanize }}%**  \n  > {{ $labels.group }}-{{ $labels.instance }}"

  - alert: NFS磁盘使用率
    expr: 100 - (node_filesystem_avail_bytes/node_filesystem_size_bytes{fstype="nfs"} * 100) > 90
    for: 5m
    labels:
      alertype: system
      severity: warning
    annotations:
      description: "**{{ $labels.name }}_{{ $labels.mountpoint }}：磁盘使用率{{ $value | humanize }}%**  \n  > {{ $labels.group }}-{{ $labels.instance }}"

  - alert: VM磁盘读写容量
    expr: (irate(node_disk_read_bytes_total[5m]) ) /1024 /1024  > 80 or (irate(node_disk_written_bytes_total[5m]) ) /1024 /1024 > 80
    for: 8m
    labels:
      alertype: disk
      severity: warning
    annotations:
      description: "**{{ $labels.name }}_{{ $labels.device }}：当前IO为{{ $value | humanize }}MB/s**  \n  > {{ $labels.group }}-{{ $labels.instance }}"

  - alert: VM网络流入（下载）数据过多
    expr: sum by(device,instance, name, group, account) (irate(node_network_receive_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'}[5m])) / 1024 / 1024 > 70
    for: 5m
    labels:
      alertype: network
      severity: warning
    annotations:
      description: "**{{ $labels.name }}：流入数据为{{ $value | humanize }}MB/s**  \n  > {{ $labels.group }}-{{ $labels.instance }}"

  - alert: VM网络流出（上传）数据过多
    expr: sum by(device,instance, name, group, account) (irate(node_network_transmit_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'}[5m])) / 1024 / 1024 > 70
    for: 5m
    labels:
      alertype: network
      severity: warning
    annotations:
      description: "**{{ $labels.name }}：流出数据为{{ $value | humanize }}MB/s**  \n  > {{ $labels.group }}-{{ $labels.instance }}"

- name: Exporter服务状态-告警
  rules:
  - alert: Exporter状态
    expr: up{job=~"windows_exporter|node_exporter"} == 0
    for: 3m
    labels:
      alertype: itself
      severity: Critical
    annotations:
      description: "**{{ $labels.job }}：异常**  \n  > {{ $labels.group }}-{{ $labels.name }}-{{ $labels.instance }}"